### ISSUE TITLE
Automatizar criação do zip para deploy

### ISSUE THREAD

**Issue by romuloalves** [romuloalves/feevale-login#4]
Deve ser automatizada a tarefa da geração do .zip de deploy, seguindo as seguintes regras:
- Utilizar grunt ou gulp (atualmente já existem as dependências do gulp); 
- Minificar os arquivos .js;
- Minificar os arquivos .css;
- Remover as classes não utilizadas de css;
- Minificar os arquivos .html;
- Criar um arquivo .zip com os arquivos necessários a publicação. Não esquecer arquivo "manifest.json".

**Comment by mkautzmann** [comment]
Partindo do princípio que o Gulp continuará sendo usado. O pacote [gulp-zip](https://github.com/sindresorhus/gulp-zip) parece bom para gerar o zip de deploy contendo tudo o que tem dentro da pasta `src`.

Esse zip poderia ser gerado numa task independente do gulp e também como passo final de uma task `build` ou mesmo a `default`.

**Comment by romuloalves** [comment]
Sim, minha ideia era uma task específica de build que gerasse o zip como resultado.
Sobre o gulp-zip, ótimo, valeu!

**Comment by romuloalves** [comment]
Criada geração do deploy no commit ceebd26406b33f607b0204e4b8e4c008219ed126.
Ainda é necessário minificar os arquivos Javascript.

**Comment by mkautzmann** [comment]
Show de bola, você já publicou na Store ou vai fazer depois de minificar?

**Comment by romuloalves** [comment]
Publiquei sem minificar por que não influencia muito mesmo.
Eu havia começado a fazer a task de minificar, porém deu erro no parser, dai removi a task e deixei assim por enquanto.
